{
 "title": "OpenWeatherMap Dashboard",
 "time": { "from": "2024-12-05T06:00:00.000Z", "to": "2024-12-10T03:00:00.000Z" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT city_name FROM weathers "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center; size:120px; font-weight:bold;\">Weather Dashboard</h1>"
   },
   "targets": [
    { "rawSql": "SELECT * FROM air_quality " }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Estimate Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT temperature, dt FROM forecasts WHERE dt >= date_trunc('day', now()) and dt < date_trunc('day', now()) + interval '7 day' and dt > now() ORDER BY weather_id DESC LIMIT 40"
    }
   ]
  },
  {
   "title": "Estimate Weather",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT weather_main AS \"Weather\", dt AS \"Date\" FROM forecasts ORDER BY weather_id DESC, id ASC LIMIT 40\n"
    }
   ]
  },
  {
   "title": "Estimate Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT humidity, dt FROM forecasts WHERE dt >= date_trunc('day', now()) and dt < date_trunc('day', now()) + interval '7 day' and dt > now() ORDER BY weather_id DESC LIMIT 40"
    }
   ]
  },
  {
   "title": "Feels Like",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT feels_like FROM weathers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT weather_description FROM weathers ORDER BY dt DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sunrise AS \"Sunrise\" FROM weathers "
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperature FROM weathers ORDER BY dt DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temp_min AS \"Temp Min\" FROM weathers ORDER BY dt DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT wind_speed AS \"Wind Speed\" FROM weathers ORDER BY dt DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select humidity AS \"Humidity\" FROM weathers ORDER BY dt DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pressure AS \"Pressure\" FROM weathers ORDER BY dt DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sunset AS \"Sunset\" FROM weathers "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temp_max AS \"Temp Max\" FROM weathers ORDER BY dt DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT so2 FROM air_quality" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT no2 FROM air_quality" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT pm10 FROM air_quality" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT aqi AS \"Air Quality\" FROM air_quality"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT pm2_5 FROM air_quality" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT o3 FROM air_quality" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT co FROM air_quality" }
   ]
  }
 ]
}