apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: dashboard-openweathermap-postgres-1:5432
    database: open_weather_map
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      sslmode: "disable"
    isDefault: true
